# Generated by Django 5.0.6 on 2024-06-01 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_remove_portfolio_total_investment_portfolio_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='name',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
