# Generated by Django 5.0.6 on 2024-06-01 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0005_remove_portfolio_name_portfolio_total_investment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='name',
            field=models.CharField(blank=True, default='Default Portfolio', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='total_investment',
            field=models.FloatField(default=0),
        ),
    ]
