# Generated by Django 5.0.6 on 2024-06-01 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0006_portfolio_name_alter_portfolio_total_investment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='name',
            field=models.CharField(default='Default Portfolio', max_length=100),
        ),
    ]
